### ISSUE TITLE
Add docker run and docker-compose.yaml

### ISSUE THREAD

**Issue by SamBouwer** [SamBouwer/any-docker#1]
To get users easily started, add a `docker run` and `docker-compose.yaml` example.

**Comment by ahmedwael216** [comment]
Can we also add a makefile?
It's usually just a bunch of aliases, but it makes life easier for anyone to get started.

Ex:
> make build -> is just a call to docker build

> make run -> is just a call to docker run

And so on...

**Comment by SamBouwer** [comment]
Definitely! I'll need to read into how to exactly do it to add it myself, but feel free to submit a pull request ;)

**Comment by SamBouwer** [comment]
@ahmedwael216 makefile is added. Learned something new again! :)
