### ISSUE TITLE
Inconsistent paths in dev setup script

### ISSUE THREAD

**Issue by dzshch** [SamBouwer/any-docker#13]
Hi! Thank you for the effort in making this repo!

In the `any-docker/scripts/setup_dev_env.sh`, there's inconsistency in paths during the GO installation:
```
if [ "${GOLANG_VER_INSTALLED}" == "go version go${GOLANG_VER} linux/amd64" ] ; then
  echo "'go version go${GOLANG_VER} linux/amd64' is already installed, skipping..."
else
  echo "Installing 'go version go${GOLANG_VER} linux/amd64'"
  wget -N https://go.dev/dl/go${GOLANG_VER}.linux-amd64.tar.gz
  tar -C /usr/local -xzf $HOME/go${GOLANG_VER}.linux-amd64.tar.gz
  rm go${GOLANG_VER}.linux-amd64.tar.gz
fi
```
The .tar file is downloaded to the current directory but is expected to be in $HOME later.

Which gives this error:
```
tar (child): /home/<username>/go1.19.11.linux-amd64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by SamBouwer** [comment]
Thanks! Should be fixed in [24d3294](https://github.com/SamBouwer/any-docker/commit/24d3294f1523399e969a3817a199ca44cedbdb55) (testing, so I'm not closing the issue yet)

**Comment by SamBouwer** [comment]
Yep, should be fixed! I needed to additional commits to get it right 😬 
[65633b8](https://github.com/SamBouwer/any-docker/commit/65633b8089db29104702bdaf77e7c2a7e7677833)
[06e44230](https://github.com/SamBouwer/any-docker/commit/06e44230c29382ebe5d8c7b2d5b63f83e344e033)

**Comment by dzshch** [comment]
Works for me as well, thanks for the fix.
