### ISSUE TITLE
No more build-heart in make file

### ISSUE THREAD

**Issue by Shampra** [SamBouwer/any-docker#17]
Hi,

`make build-heart` does not exist (or no longer exists) in the make file. I'm assuming that since it's built into "_**build-client**_", it's been removed and all you have to do is update the readme file?

_(no big deal compared to all the mistakes I've made, but hey...)_

**Comment by SamBouwer** [comment]
Correct. I've started the process to remove all references to the `make build-heart` make command in favour of the `make build-client-*` commands as the anytype-heart needs to be built for every platform individually, so it did not really make sense to build it all at once for all platforms to only then use the relevant parts when building clients.  

I've hopefully addressed the issue in https://github.com/SamBouwer/any-docker/commit/6986ff7f3f56a97a5c1d82d84c3cc6cb3974e681
