### ISSUE TITLE
Ubuntu WLS2 : Package 'docker-ce' unavailable

### ISSUE THREAD

**Issue by Shampra** [SamBouwer/any-docker#18]
setup_dev_env.sh has a problem with me.

Environment : VM Windows 11 (dev image by Microsoft), WSL2, Ubuntu 22.04.2 LTS

`   sudo apt-get install -y --no-install-recommends \
...
` cannot find package

Error : 
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
E: Unable to locate package docker-ce-cli
E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
E: Unable to locate package docker-buildx-plugin
E: Unable to locate package docker-compose-plugin
```

Impact : it doesn't seem to install any packages, generating errors afterwards (notably jq and non-existent unzip).
I had to manually install the missing packages

**Comment by SamBouwer** [comment]
Testing this now on Ubuntu on WSL2 on Win11 :)

**Comment by SamBouwer** [comment]
@Shampra Could you pull the latest version of the script and see whether it now works? (you might need to start fresh or at least remove the manually installed packages)

Should be resolved by this change: https://github.com/SamBouwer/any-docker/commit/98132da6bba6688d0e7880f1c3596e6bbc464d95

**Comment by Shampra** [comment]
it seems to work (the script checks versions for unzip and jq whereas before it stopped).
I'd have to do another test in a blank environment, but I can't at the moment.

**Comment by SamBouwer** [comment]
Closing for now, @Shampra let me know if you still have issues on WSL2
