### ISSUE TITLE
WSL : cannot communicate with server snapcraft

### ISSUE THREAD

**Issue by Shampra** [SamBouwer/any-docker#22]
Trying to build clients, following readme.

On `make setup-dev-env`, I have this error : 

```
+ sudo snap install snapcraft --classic
error: cannot communicate with server: Post "http://localhost/v2/snaps/snapcraft": dial unix /run/snapd.socket: connect: no such file or directory
make: *** [Makefile:53: setup-dev-env] Error 1
```

**Environment** : 
- Windows 11
- WSL Ubuntu 22.04.2 LTS
- system.d active

(and after that, if I launch make build-client-win, it crash, I'm not sure if it's related to this issue or independent)
![image](https://github.com/SamBouwer/any-docker/assets/16141040/1b637fa5-7fba-405e-99bf-97cd76446037)

**Comment by SamBouwer** [comment]
Do you have `systemd` enabled in WSL? If not, or if unsure, check this post:

https://askubuntu.com/questions/1379425/system-has-not-been-booted-with-systemd-as-init-system-pid-1-cant-operate/1379567#1379567

I have systemd enabled on my installation and snap installs fine.

**Comment by SamBouwer** [comment]
See also these comments in the readme:

> ℹ️ Note: if you are running this in WSL, make sure to add the following lines to /etc/wsl.conf to ensure snap can be installed:
```
[boot]
systemd=true
```

Then run `wsl.exe --shutdown`

**Comment by Shampra** [comment]
I've already check that too 😞.
I'll delve into it further as soon as I can.

**Comment by SamBouwer** [comment]
Check if you need to upgrade to npm 16 btw! You seem to be running node 12. I noticed I was on node 10 for a while and that cause A LOT of issues :P. I use nvm now to manage node and npm versions, but seeing your level of experience I guess you are already familiar with that :).

**Comment by Shampra** [comment]
> I use nvm now to manage node and npm versions, but seeing your level of experience I guess you are already familiar with that :).

😅 I would like to, but no, I'm starting to work on AT. In development, I mainly use C# with Visual Studio. JS, Linux, Git, I had very basic knowledge.

Ticket closed, it's works.
What I've done, for reference : 
- reset WSL
- restart completly the computer (VM here) because I've other strange things with this WSL... and reboot is the answer to everything!
- `wsl --update` (already done but with error before, I should have insisted)
- Try again `make setup-dev-env`, it's work 👌
