### ISSUE TITLE
Android client

### ISSUE THREAD

**Issue by ippocratis** [SamBouwer/any-docker#9]
I don't see an option to select a custom server on the android app.
I don't see android client on the makefile.
I see the checkmark on the android Middleware library in the project status.
I'm not sure I undestand what that is.
Is there a way to use the android app and sync to my custom anytime node?

Thank you for  bringing docker as an option for selfhosting anytype.

Keep up

**Comment by ippocratis** [comment]
Nevermind
just saw the hourglash icon under android client on the project status.
I'll have to wait

Sorry I rushed to open an issue

Closing

**Comment by SamBouwer** [comment]
> I don't see an option to select a custom server on the android app.

Correct, for all clients the connection details are hard coded into the app during building. 

> I don't see android client on the makefile.

Good point, I will add it! Building the Anytype app for Android is not working yet, so it won't help that much at this stage ;). 

> I see the checkmark on the android Middleware library in the project status.

Middleware libraries are (supposedly) build properly for all for all platforms, but we will only find out whether it's actually correct when the clients are build as well. I'm working on the Windows client right now. 

> I'm not sure I undestand what that is.
> Is there a way to use the android app and sync to my custom anytime node?

So, unless we get the Android client to build correctly (can't think of the exact error I'm stuck at atm) there is no way to use the Android app with your own nodes. 

> Thank you for  bringing docker as an option for selfhosting anytype.
> Keep up 

Thanks! My priorities are nodes > Windows client > Android client, and then the rest ;) and I'm definitely open to suggestions on how to improve my setup!
